# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Wyszukiwarka wolnych terminów szczepień przeciw COVID-19
description: >- # this means to ignore newlines until "baseurl:"
  Pomoc przy wyszukiwaniu wolnych terminów na szczepienia przeciw COVID-19.
url: "https://szczepienia.github.io"

markdown: GFM
theme: minima
google_analytics: G-C7CYKR13N5
timezone: Europe/Warsaw

lang: pl
twitter_username: krzyk

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
